import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-black shadow">
          <div className="max-w-6xl mx-auto px-4 py-4 flex justify-between items-center">
            <div className="text-2xl font-bold">PriceView</div>
            <nav className="flex gap-6">
              <a href="/" className="hover:text-gray-600">Home</a>
              <a href="/about" className="hover:text-gray-600">About</a>
              <a href="/contact" className="hover:text-gray-600">Contact</a>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}